export const START_ASYNC_REQUEST = 'START_ASYNC_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const CATCH_ERROR = 'CATCH_ERROR';

export const SHOW_MOVIE_DETAILS = 'SHOW_MOVIE_DETAILS';
export const CLOSE_MOVIE_DETAILS = 'CLOSE_MOVIE_DETAILS';

export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
